# title: Minimal theme
# logo: /assets/img/logo.png
# description: Minimal is a theme for GitHub Pages.
# show_downloads: true
# google_analytics:
# theme: jekyll-theme-minimal

title: Shu Zhang
logo: /assets/img/head.png
# description: About Shu Zhang
description: Welcome to Shu ZHANG's Page.
email_link: zhangshu(at)ouc(dot)edu(dot)cn
# postal_addr_link: College of Information Science and Engineering, Ocean University of China | 238 Songling Road, Qingdao, China | Postal code 266100
OUC_link: http://it.ouc.edu.cn/2019/0527/c16104a248647/page.htm
google_scholar_link: https://scholar.google.com/citations?user=YB0KgA4AAAAJ&hl=en
scopus_link: http://www.scopus.com/inward/authorDetails.url?authorID=56366331000&partnerID=MN8TOARS
# scopus_link: https://www.scopus.com/authid/detail.uri?authorId=56366331000
site.show_downloads: false
site.github.is_project_page: false
site.github.is_user_page: false
google_analytics:
theme: jekyll-theme-minimal

# Author Settings
# author: David Freeman # add your name
# author-img: david-freeman.jpg # add your photo
# about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
# social-github: artemsheludko # add your Github handle
# social-linkedin: # add your Linkedin handle
# social-email: # add your Email address
# social-email: zhangshu(at)ouc(dot)edu(dot)cn
